### ISSUE TITLE
Forward Compatibility

### ISSUE THREAD

**Issue by robmoffat** [deutschebank/symphony-java-client-parent#33]
If Symphony add fields to the JSON, this causes problems for versions of bindings that don't know about these fields.

```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "sid" (class com.symphony.api.model.V4Message), not marked as ignorable (12 known properties: "attachments", "messageId", "externalRecipients", "timestamp", "message", "originalFormat", "data", "user", "stream", "diagnostic", "userAgent", "disclaimer"])
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 2192] (through reference chain: com.symphony.api.model.V4EventList[0]->com.symphony.api.model.V4Event["payload"]->com.symphony.api.model.V4Payload["messageSent"]->com.symphony.api.model.V4MessageSent["message"]->com.symphony.api.model.V4Message["sid"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
```

**Comment by robmoffat** [comment]
Not entirely solved, I think.

I am sometimes seeing this problem happening again.  Ivan Rodriguez's fix seems to work sometimes:

```
spring:
  jackson:
    FAIL_ON_UNKNOWN_PROPERTIES: false
```

Not sure why this is even being used for setting up our symphony clients.

**Comment by robmoffat** [comment]
This is caused anytime you have jersey-media-json-jackson on the class path.  Sadly, I have left this in the symphony-api-spring-boot-starter, so I need to do a new release with this.
